color: null
description: null
fieldLayouts:
  49b8050a-b501-4b42-8887-6b35853e1ae8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-06T09:30:56+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2637b2bd-d6c6-4e39-bda0-71a6fe6ab363
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-06T09:34:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7cff06a0-49d2-439f-8751-325a9a315ad4 # Subline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c9995a16-95c4-45f5-b437-e58cd4054769
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-06T09:45:50+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c28cfb53-589c-4ae1-854d-c791f99d84f7 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 59e770a5-8c6f-4f22-91ec-bbfda5ff9f87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-06T09:39:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b169acdd-3b36-4e75-986a-73938f03732d # Bild
            handle: bgImg
            includeInCards: false
            instructions: null
            label: 'Background Image'
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 819d1269-d990-4114-beda-c7e77923ff33
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: a6183249-65d3-4c8d-b6b5-2558fc91cdd2
        userCondition: null
handle: actionModule
hasTitleField: true
icon: wave-pulse
name: 'Call Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
