color: null
description: null
fieldLayouts:
  a0ce64c1-3871-49cb-bdf0-cdf580678fb5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-09T13:04:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ea2a6233-2f58-4bd6-bd49-aaba7c2c7b1c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-09T13:07:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7cff06a0-49d2-439f-8751-325a9a315ad4 # Subline
            handle: null
            includeInCards: false
            instructions: null
            label: Beschreibung
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 535215b1-1c45-42e0-b79f-fd950a7e64e9
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 17c863d8-f0a1-4bd6-a79f-895936d578d6
        userCondition: null
handle: serviceModule
hasTitleField: true
icon: cart-flatbed-boxes
name: 'Dienstleistungen Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
