color: null
description: null
fieldLayouts:
  586a2b15-1c36-4256-aa10-88c2e547131d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-08T13:48:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f9e8f838-1fcd-46e8-8877-a7405e65e37f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-08T13:50:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b169acdd-3b36-4e75-986a-73938f03732d # Bild
            handle: geojson
            includeInCards: false
            instructions: null
            label: JSON
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9db256b9-b264-450c-ab91-24045b6e55d3
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d3a5375d-9002-4d27-9cb1-652e724b2e05
        userCondition: null
handle: testMapModule
hasTitleField: true
icon: null
name: 'Test Map Module'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
