color: null
description: null
fieldLayouts:
  30621e82-69ac-45c1-bbf0-2ec9782c0947:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-06T10:08:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb54101d-5f34-4510-a792-68f7097eb873
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-06T10:11:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5ba99515-4f13-4bcb-af24-9cb0e1f15924 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abce2747-6d81-4817-9c7e-e786b6bc262d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-06T10:11:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b169acdd-3b36-4e75-986a-73938f03732d # Bild
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70a824cd-796f-4d21-9b11-52799239a5e5
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 6c9c3bcb-1f41-466b-a974-9b50caf1c2b1
        userCondition: null
handle: textImage
hasTitleField: true
icon: bars-progress
name: 'Text Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
