altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  26c68e5b-8858-4d60-b87b-275febe5c21f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-28T10:11:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 741b4a23-c7b0-4205-a277-1458098ff7d4
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 5baad6cf-17fc-4303-b741-9ea4124c4734
        userCondition: null
fs: general
handle: general
name: Allgemein
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
