columnSuffix: null
handle: dontShowInMenu
instructions: null
name: 'Nicht im Hauptmenu anzeigen'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
