columnSuffix: null
handle: showInFooter
instructions: null
name: 'Im Footermen√º anzeigen'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
