columnSuffix: null
handle: textTable
instructions: null
name: 'Inhalt Tabelle'
searchable: false
settings:
  addRowLabel: 'Zeile hinzuf√ºgen'
  columns:
    __assoc__:
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - Headline
            -
              - handle
              - headline
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - Text
            -
              - handle
              - text
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col3
          - ''
        -
          - col4
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
