fieldLayouts:
  2a12fc40-45b8-4cab-bb6a-9423e8544b6f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-01-08T14:28:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b169acdd-3b36-4e75-986a-73938f03732d # Bild
            handle: bgImg
            includeInCards: false
            instructions: null
            label: 'Hintergrund Bild'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18607b58-db12-4283-b6a1-67459642f158
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-01-28T08:35:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b169acdd-3b36-4e75-986a-73938f03732d # Bild
            handle: logo
            includeInCards: false
            instructions: null
            label: Logo
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec9f5887-72c6-492b-94ee-5d527e81c624
            userCondition: null
            warning: null
            width: 50
        name: Inhalt
        uid: a22c1906-4857-41ee-924d-2fc3f389f328
        userCondition: null
handle: global
name: Allgemein
sortOrder: 1
