defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cd4c7ee7-c50f-4f66-80d0-1811555f50d0 # Drone Index
handle: drones
maxAuthors: 1
name: Drones
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: drones/_entry.twig
    uriFormat: 'drones/{slug}'
type: channel
