defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e783066e-ab8f-45aa-9b5c-74681a830222 # FAQ
handle: faq
maxAuthors: 1
name: FAQ
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: faq/_entry.twig
    uriFormat: 'faq/{slug}'
type: channel
