defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b455a4e7-544b-4cd3-810f-db4ab5a1e876 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: __home__
type: single
