defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: caf20086-7c79-4c23-b1da-55529195e0ca # Seite
  -
    uid: cc0cdf27-7055-4073-a3b7-b6b74a880c14 # Map Index
handle: pages
maxAuthors: 1
name: Seiten
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: e1e580c8-45c0-426f-a87f-5f6be61db045
type: structure
