defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 69c3e1f4-03d9-4975-8e6a-4f7ecf3110c6 # Staff Box
handle: personal
maxAuthors: 1
name: Mitarbeiter
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: staff/_entry.twig
    uriFormat: 'staff/{slug}'
structure:
  maxLevels: null
  uid: 46d3f851-ea9a-449b-9c02-fa16c9e13cbf
type: structure
