defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: aff89e48-c9a5-43d9-8277-d099fa7f133f # Dienstleistungen
handle: services
maxAuthors: 1
name: Dienstleistungen
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: services/_entry.twig
    uriFormat: 'services/{slug}'
type: channel
