defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e127daa5-093b-4928-a45e-74eaeda33c80 # Text Image
handle: textImage
maxAuthors: 1
name: 'Text Image'
previewTargets:
  -
    label: 'Prim√§re Eintrag Seite'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae577999-1044-43a3-872e-03346ef0d0b4: # SkyCrew
    enabledByDefault: true
    hasUrls: true
    template: text-image/_entry.twig
    uriFormat: 'text-image/{slug}'
type: channel
